//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int id_Users { get; set; }
        public int id_Group { get; set; }
        public int id_Progr { get; set; }
        public int id_News { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual News News { get; set; }
        public virtual Progress Progress { get; set; }
        public virtual Users Users { get; set; }
    }
}
