//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public int id_Users { get; set; }
        public Nullable<int> id_Group { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Users Users { get; set; }
    }
}
