//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int idTest { get; set; }
        public string Questions { get; set; }
        public string answerOption_1 { get; set; }
        public string answerOption_2 { get; set; }
        public string answerOption_3 { get; set; }
        public Nullable<int> Answer { get; set; }
    }
}
